function setup() {
    // Setup code goes here.
    // This function runs once.
    // The default canvas size, which is implied here, is 100 × 100 in pixels.
    // The 1-pixel gray border around the box is generated by style.css.
}

function draw() {
    stroke(255, 0, 0);
    point(5, 5);

    stroke(0, 255, 255);
    point(95, 5);

    stroke(0, 0, 255);
    point(5, 95);

    stroke(255, 0, 255);
    point(95, 95);
}
