function setup() {
    // Setup code goes here.
    // This function runs once.
    // The default canvas size, which is implied here, is 100 × 100 in pixels.
    // The 1-pixel gray border around the box is generated by style.css.
}

function draw() {
    point(5, 5);
    point(95, 5);
    point(5, 95);
    point(95, 95);
}
